### ISSUE TITLE
Pointer bugs, use different method for toggling

### ISSUE THREAD

**Issue by btrussin** [btrussin/UMD_VR#7]
pointer gets turned off under a lot of conditions; such as when any menu is closed, even when there are other menus still open

I suggest making some function that detects if any menu is open and using that as a guideline for whether or not that have the pointer active.

Bonus: Detect if the controller is facing a menu and only display the pointer if it is.  This would eliminate the problem of deciding which controller (left or right) has the pointer

**Comment by MikhailSorokin** [comment]
I would like to discuss the menu thing with both you and Celeste on Monday as I have an idea for how menus can be handled that doesn't involve them being in world space and being potentially occluded by other existing menus.
